/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JMenuItem;
import javax.swing.JTable;
import javax.swing.JTextField;
import services.operacao.IDado;

/**
 *
 * @author daniel
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    private IDado dados; 
    
    public PrincipalView(IDado dados) {
        initComponents();
        
        this.dados = dados;
        
        this.setLocationRelativeTo(this.getParent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        mbPrincipal = new javax.swing.JMenu();
        btn_importarDados = new javax.swing.JMenuItem();
        btn_CalcularEstatistica = new javax.swing.JMenuItem();
        btn_VisualizarResultado = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora Estatistica");

        lblQuantidade.setText("Quantidade");

        txtQuantidade.setToolTipText("");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        mbPrincipal.setText("Operações");

        btn_importarDados.setText("Importar Dados");
        btn_importarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_importarDadosActionPerformed(evt);
            }
        });
        mbPrincipal.add(btn_importarDados);

        btn_CalcularEstatistica.setText("Calcular Estatistica");
        btn_CalcularEstatistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CalcularEstatisticaActionPerformed(evt);
            }
        });
        mbPrincipal.add(btn_CalcularEstatistica);

        btn_VisualizarResultado.setText("Visualizar Resultado");
        mbPrincipal.add(btn_VisualizarResultado);

        menuBar.add(mbPrincipal);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblQuantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantidade))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_importarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_importarDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_importarDadosActionPerformed

    private void btn_CalcularEstatisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CalcularEstatisticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CalcularEstatisticaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btn_CalcularEstatistica;
    private javax.swing.JMenuItem btn_VisualizarResultado;
    private javax.swing.JMenuItem btn_importarDados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JMenu mbPrincipal;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables

    public JTable getTable() {
        return table;
    }

    public JTextField getTxtQuantidade() {
        return txtQuantidade;
    }

    public JMenuItem getBtn_CalcularEstatistica() {
        return btn_CalcularEstatistica;
    }

    public JMenuItem getBtn_VisualizarResultado() {
        return btn_VisualizarResultado;
    }

    public JMenuItem getBtn_importarDados() {
        return btn_importarDados;
    }
}
